INSERT INTO MEMBER(M_ID,M_PW,M_NUMBER,M_NICKNAME) VALUES
("USER0001","12341234","010-1234-1234","유저1");


INSERT INTO CATEGORY(CA_NAME, CA_CODE) VALUES
("커피","COF");


INSERT INTO MENU(ME_CODE, ME_CA_NUM, ME_NAME, ME_PRICE, ME_CONTENT, ME_THUMB, ME_HOT_ICE) VALUES
("COF001",1,"아메리카노",1500, "진한 커피", "COFFEE.AMERICANO.JPG", "I");
INSERT INTO MENU(ME_CODE, ME_CA_NUM, ME_NAME, ME_PRICE, ME_CONTENT, ME_THUMB, ME_HOT_ICE) VALUES
("COF002",1,"아메리카노",1500, "마음을 녹여주는 커피", "COFFEE.AMERICANO.JPG", "H");


INSERT INTO CART(CT_M_ID) VALUES
("USER0001");

INSERT INTO CART_LIST(CL_ME_CODE, CL_CT_NUM, CL_AMOUNT) VALUES
("COF001",1,2),("COF002",1,1);

INSERT INTO `order`(OR_CT_NUM, OR_M_ID, OR_USE, OR_TOTAL, OR_FINAL) VALUES
(1, "USER0001", 0, 4500, 4500);

INSERT INTO STAMP(ST_M_ID, ST_COUNT) VALUES
("USER0001", 0);

update stamp
set ST_COUNT = ST_COUNT+1
where ST_M_ID = "user0001";


INSERT INTO COUPON(CO_M_ID, CO_COUNT) VALUES
("USER0001", 2);

update coupon
set CO_COUNT = CO_COUNT+1
where CO_M_ID = "user0001";

UPDATE cart
SET CT_STATUS = "Y"
WHERE CT_NUM = 1;

INSERT INTO income(IN_MONEY) VALUES
();