INSERT INTO MEMBER(M_ID,M_PW,M_NUMBER,M_NICKNAME,M_AUTHORITY) VALUES
("admin","admin","010-1234-1234","관리자","ADMIN");


INSERT INTO CATEGORY(CA_NAME, CA_CODE) VALUES
("커피","COF");

INSERT INTO MENU(ME_CODE, ME_CA_NUM, ME_NAME, ME_PRICE, ME_CONTENT, ME_THUMB, ME_HOT_ICE) VALUES
("COF001",1,"아메리카노",1500, "진한 커피", "COFFEE.AMERICANO.JPG", "I");
INSERT INTO MENU(ME_CODE, ME_CA_NUM, ME_NAME, ME_PRICE, ME_CONTENT, ME_THUMB, ME_HOT_ICE) VALUES
("COF002",1,"아메리카노",1500, "마음을 녹여주는 커피", "COFFEE.AMERICANO.JPG", "H");
